### ISSUE TITLE
Mua

### ISSUE THREAD

**Issue by Tacther** [KagurazakaSarah/KagurazakaSarah#1]
I’m so fucking love you. Get merry with me, plz. I want you to kiss my ass, and be my lover.

**Comment by KagurazakaSarah** [comment]
Dear Tacther，
     Dirnk Mroe Hto Wtare。
     (Because of my Chinese's English，I think you can't understood me meaning，EXCUSE MINE。
     By the way,My English vocabulary is waek,so plaese comment with Chnises later。
     See you later!

**Comment by KagurazakaSarah** [comment]
啊嘞，Whrer is you 脑子接口，你怎么不SPEAK了。

**Comment by KagurazakaSarah** [comment]
如果您没有其它问题的话，我就关掉这个议题了，对您带来的不便，敬请谅解。
